# Generated by Django 2.2.7 on 2019-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_auto_20191127_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
